name: Build & test

on: [push, pull_request]


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.compiler }}-${{ matrix.phase }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        compiler: [GCC, CLANG]
        phase: [BUILD, DEFAULT_TESTS, MULTIBYTE_LOCALES_TESTS, DISABLE_SHOPTS_TESTS, SHOPT_SCRIPT_ONLY_TESTS]
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Install build & test dependencies
        run: |
          sudo dnf install -y dnf-plugins-core clang
          sudo dnf install -y util-linux glibc-langpack-ja ncurses procps tzdata sed
          sudo dnf builddep -y ksh

      - name: Build & test
        run: sudo --preserve-env=GITHUB_ACTIONS,CI .github/workflows/ci.sh ${{ matrix.compiler }} ${{ matrix.phase }}
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: ksh-logs

